## Purpose: to compare the analytical probability models for the spatial
## abundance distribution with that generated by the community simulator

setwd('/home/danmcglinn/maxent/spat')

source('spat_analytical_prob_funcs.R')

## generate some comparitive frequency distributions
## example from pg 96 fig 4.1
pdf('analytical_prob_funcs.pdf',width=14,height=7)
par(mfrow=c(1,2))
no = 100
n = 0:5
Ao = 64
A = 1
out = matrix(NA,nrow=6,ncol=length(n))
out[1,] = piBin(n,A,no,Ao)
out[2,] = piLap(n,A,no,Ao)
out[3,] = piHEAP(n,A,no,Ao)
out[4,]= piMETE(n,A,no,Ao)
out[5,]= piMETEiter(n,A,no,Ao)
out[6,] = piNegBi(n,A,no,Ao)


plot(n,out[1,],ylim=range(out,na.rm=TRUE),type='n',ylab='Probabiliy',
     main='No = 100, A = Ao/64')
for(i in 1:4)
  lines(n,out[i,],col=i,type='l',lwd=2)
for(i in 5:6)
 points(n,out[i,],col=i,pch=19,cex=1.5)
legend('topright',c('bin','lap','heap','mete','meteiter','negbin(k=1)'),col=1:6,
       lwd=c(rep(3,4),NA,NA),lty=c(rep(1,4),NA,NA),pch=c(rep(NA,4),19,19),cex=2,bty='n')
## lap, mete and negbi are equivalent
## heap and meteiter are equivalent

no = 5
n = 0:5
Ao = 4
A = 1

out = matrix(NA,nrow=6,ncol=length(n))
out[1,] = piBin(n,A,no,Ao)
out[2,] = piLap(n,A,no,Ao)
out[3,] = piHEAP(n,A,no,Ao)
out[4,]= piMETE(n,A,no,Ao)
out[5,]= piMETEiter(n,A,no,Ao)
out[6,] = piNegBi(n,A,no,Ao)

plot(n,out[1,],ylim=range(out,na.rm=TRUE),type='n',ylab='Probability',
     main='No = 5, A = Ao/4')
for(i in 1:4)
  lines(n,out[i,],col=i,type='l',lwd=2)
for(i in 5:6)
 points(n,out[i,],col=i,pch=19,cex=1.5)
legend('topright',c('bin','lap','heap','mete','meteiter','negbin(k=1)'),col=1:6,
       lwd=c(rep(3,4),NA,NA),lty=c(rep(1,4),NA,NA),pch=c(rep(NA,4),19,19),cex=2,bty='n')
## mete and negbi are equivalent
## heap and meteiter are equivalent
dev.off()

S = round(10^seq(log10(10),log10(100),length.out=20))
N = round(10^seq(log10(120),log10(5e5),length.out=20))

comms = read.csv(paste('./comms/simulated_comms_S',S[1],'_N',N[1],
                '_C200_B13_grid.txt',sep=''),header=TRUE)
comm1 = as.matrix(comms[comms[,1]==1,-(1:3)])
filler = matrix(rep(1:max(comm1),each=ncol(comm1)),nrow=max(comm1),byrow=TRUE)
cnts = apply(rbind(comm1,filler),2,table)-1
freqs = cnts/nrow(comm1)
no = apply(comm1,2,sum)
n = 1:max(comm1)
Ao = nrow(comm1)

i = 4
plot(n,freqs[-1,i],log='y')
lines(n,piMETE(n,1,no[i],Ao),col='red')



