## Purpose: to compare the analytical probability models for the spatial
## abundance distribution with that generated by the community simulator

setwd('/home/danmcglinn/maxent/spat')

source('spat_analytical_prob_funcs.R')
dyn.load('heap.so')
## generate some comparitive frequency distributions
## example from pg 96 fig 4.1
#pdf('analytical_prob_funcs.pdf',width=14,height=7)
par(mfrow=c(1,2))
no = 112
n = 0:5
Ao = 64
A = 1
out = matrix(NA,nrow=4,ncol=length(n))
out[1,] = piBin(n,A,no,Ao)
out[2,] = piLap(n,A,no,Ao)
out[3,] = piHEAPfast(n,A,no,Ao)
out[4,] = piNegBi(n,A,no,Ao)

comms = read.csv('./comms/simulated_comms_S1_N112_C500_B7_grid.txt',header=TRUE)
comms = as.matrix(comms)
## reshape for ease of analysis
Ncomms = 500
Nquads = 64

commMat = matrix(comms[,4],ncol=Ncomms,nrow=Nquads)
filler = matrix(rep(0:max(commMat),each=ncol(commMat)),nrow=max(commMat)+1,byrow=TRUE)
cnts = apply(rbind(commMat,filler),2,table) - 1
freqs = cnts/nrow(commMat)
freqAvg = apply(freqs,1,mean)

plot(n,out[1,],ylim=range(out,na.rm=TRUE),type='n',ylab='Probabiliy',
     main=paste('No = ',no,', A = Ao/',Ao,sep=''))
for(i in 1:3)
  lines(n,out[i,],col=i,type='l',lwd=2)
points(n,out[4,],col=4,pch=19,cex=1.5)
points(0:5,freqAvg[1:6],cex=1.5) ## Matches perfectly with HEAP from Fig 4.1
legend('topright',c('bin','lap','heap','negbin(k=1)','simulator'),
       col=c(1:4,1),lwd=c(rep(3,3),rep(NA,2)),lty=c(rep(1,3),rep(NA,2)),
       pch=c(rep(NA,3),19,1),cex=2,bty='n')
## lap, mete and negbi are equivalent
## heap and meteiter are equivalent

no = 5
n = 0:5
Ao = 4
A = 1

out = matrix(NA,nrow=4,ncol=length(n))
out[1,] = piBin(n,A,no,Ao)
out[2,] = piLap(n,A,no,Ao)
out[3,] = piHEAPfast(n,A,no,Ao)
out[4,] = piNegBi(n,A,no,Ao)

comms = read.csv('./comms/simulated_comms_S1_N5_C500_B3_grid.txt',header=TRUE)
comms = as.matrix(comms)
## reshape for ease of analysis
Ncomms = 500
Nquads = 4

commMat = matrix(comms[,4],ncol=Ncomms,nrow=Nquads)
filler = matrix(rep(0:max(commMat),each=ncol(commMat)),nrow=max(commMat)+1,byrow=TRUE)
cnts = apply(rbind(commMat,filler),2,table) - 1
freqs = cnts/nrow(commMat)
freqAvg = apply(freqs,1,mean)

plot(n,out[1,],ylim=range(out,na.rm=TRUE),type='n',ylab='Probability',
     main='No = 5, A = Ao/4')
for(i in 1:3)
  lines(n,out[i,],col=i,type='l',lwd=2)
points(n,out[4,],col=4,pch=19,cex=1.5)
points(0:5,freqAvg[1:6],cex=1.5) ## Matches perfectly with HEAP from Fig 4.1
legend('topright',c('bin','lap','heap','negbin(k=1)','simulator'),
       col=c(1:4,1),lwd=c(rep(3,3),rep(NA,2)),lty=c(rep(1,3),rep(NA,2)),
       pch=c(rep(NA,3),19,1),cex=2,bty='n')
## mete and negbi are equivalent
## heap and meteiter are equivalent
#dev.off()

