library(vegan)

setwd('~/maxent/spat')

source('./scripts/spat_sim_vario_func.R')

## simulated random matrices of abundance and examine if the expections
## generated by the sorExp function is correct


S = 10   ## number of species
nbar = 2    ## mean number of individuals per species 
N = 20       ## number of quadrats

comm_mat = replicate(S, rpois(N, lambda = 1))
abu = apply(comm_mat, 2, sum)

## for a single simulation 
## examine if spAvgExpPoi is working correctly
get_avg_SR = function(mat, size, reps) {
  if (size == 1)
    mean(replicate(reps, sum(mat[sample(N, size=1), ] > 0)))
  else
    mean(replicate(reps, sum(apply(mat[sample(N, size=size), ] > 0, 2, sum) > 0)))
}

expSR = sapply(1:N, function(x) spAvgExpPoi(x/N, x/N, abu))
obsSR = sapply(1:N, function(x) get_avg_SR(comm_mat, x, 100))

plot(obsSR, ylim=range(c(expSR, obsSR)), type='o', xlim=c(1,10))
lines(expSR, col='red')

## the above test demonstrates that spAvgExpPoi is correct

## examine if spCommExpPoi is working correctly
## should return the expected number of species in common
get_avg_Comm = function(mat, reps) {
  mean(replicate(reps, sum(apply(mat[sample(N, size=2), ] > 0 , 2, sum) == 2)))
}

expComm = spCommExpPoi(1/N, 1/N, abu)
obsComm = get_avg_Comm(comm_mat, 100)

expComm - obsComm

## that is a reasonable margin of error, so spCommExpPoi is correct

## this indicates that if the function sorExp fails for abundance data
## then it is computing a quantity that is fundamentally different than the 
## quantity computed by vegdist(x)
## So what is the quantity calculated by the function vegdist for bray curtis
## with quantative data?

m = comm_mat[1:2, ]
sum(abs(m[1,] - m[2,])) / sum(m[1,] + m[2,])
vegdist(m, method='bray')
vegdist(m, method='bray', binary=TRUE)
m = (m > 0) * 1
sum(abs(m[1,] - m[2,])) / sum(m[1,] + m[2,])
## above can be verbally understood as
## total difference in abundance / total abundance
## or in a binary context
## number of species not in common / species in 1 + species in 2
## a: species in sample 1, b: species in sample 2, c: species in common
## a + b / a + b + 2c
## the similarity index is defined as
## 2c / a + b + 2c
sum((m[1,] + m[2,]) == 2) / mean(apply(m, 1, sum))
1 - vegdist(m, method='bray')

## so the formula listed in ?vegdist was accurate for what the function carries out
## the quantiative version is a direct extension of the binary version


S = 250   ## number of species
nbar = 2    ## mean number of individuals per species 
N = 1e2       ## number of quadrats
nSims = 100  ## number of simulations to run

resid_abu = rep(NA, nSims)
resid_bin = rep(NA, nSims)
for (i in 1:nSims) {
  comm_mat = replicate(S, rpois(N, lambda = 1))
  abu = apply(comm_mat, 2, sum)
  exp_comm_abu = spCommExpPoi(1/N, 1/N, abu)
  exp_sr_abu = spAvgExpPoi(1/N, 1/N, abu)
  exp_abu = sorExp(comm_mat, 1)
  obs_abu = 1 - mean(vegdist(comm_mat, method="bray"))
  exp_bin = sorExp(comm_mat > 0, 1)
  obs_bin = 1 - mean(vegdist(comm_mat > 0, method="bray"))
  resid_abu[i] = exp_abu - obs_abu  
  resid_bin[i] = exp_bin - obs_bin
}

par(mfrow=c(2,1))
plot(density(resid_abu, na.rm=TRUE))
plot(density(resid_bin, na.rm=TRUE))





